name: Build and Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      version:
        description: "Version number (e.g., 1.0.0)"
        required: true
        default: "0.0.1"

permissions:
  contents: write
  actions: read

jobs:
  build-and-release:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16"

      - name: Install just
        uses: taiki-e/install-action@just

      - name: Build distribution packages
        run: just dist

      - name: Get version from justfile
        id: version
        run: echo "version=$(just get-version)" >> $GITHUB_OUTPUT

      - name: Upload DMG artifact
        uses: actions/upload-artifact@v4
        with:
          name: EmojiNinja-v${{ steps.version.outputs.version }}-dmg
          path: dist/*.dmg

      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: EmojiNinja-v${{ steps.version.outputs.version }}-zip
          path: dist/*.zip

      - name: Upload checksums
        uses: actions/upload-artifact@v4
        with:
          name: checksums
          path: dist/checksums.txt

      - name: Create Release
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.dmg
            dist/*.zip
            dist/checksums.txt
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
